### ISSUE TITLE
Not working with activator 1.3.7 and play 2.5.0

### ISSUE THREAD

**Issue by sriramkp** [dcaoyuan/nbsbt#18]
**Please find the below exception:**

[info] About to create NetBeans project files for your project(s).
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lsc
alaz/syntax/ValidationV;
        at org.netbeans.nbsbt.core.package$.setting(package.scala:66)
        at org.netbeans.nbsbt.core.NetBeans$.skipParents(NetBeans.scala:581)
        at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply$mcZ$sp(NetBe
ans.scala:108)
        at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply(NetBeans.sca
la:108)
        at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply(NetBeans.sca
la:108)
        at scala.Option.getOrElse(Option.scala:120)
        at org.netbeans.nbsbt.core.NetBeans$.action(NetBeans.scala:108)
        at org.netbeans.nbsbt.core.NetBeans$$anonfun$netbeansCommand$2.apply(Net
Beans.scala:87)
        at org.netbeans.nbsbt.core.NetBeans$$anonfun$netbeansCommand$2.apply(Net
Beans.scala:87)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.sca
la:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.sca
la:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.sca
la:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.sca
la:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:54)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Obj
ect;)Lscalaz/syntax/ValidationV;
[error] Use 'last' for the full log.
